env:
  shared-node-browser: true
  es2020: true

extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: ./tsconfig.json
