name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Configure Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn publish --access public --provenance
